I18n.pl                      =
menu                         :
schema                       : "Schemat"
new                          : "Nowy ..."
load                         : "Załaduj ..."
save                         : "Zapisz"
save_as                      : "Zapisz jako ..."
templates                    : "Szablony ..."
properties                   : "Właściwości ..."
share                        : "Udostępnij ..."
import                       : "Importuj ..."
edit                         : "Edytuj"
undo                         : "Cofnij"
redo                         : "Powtórz"
insert                       : "Wstaw"
table                        : "Tabela"
note                         : "Notatka"
view                         : "Widok"
show_minimap                 : "Pokaż minimape"
hide_minimap                 : "Schowaj minimape"
show_sidebar                 : "Pokaż sidebar"
hide_sidebar                 : "Schowaj sidebar"
show_grid                    : "Pokaż siatkę"
hide_grid                    : "Schowaj siatkę"
sort_items                   : "Sortuj tabele"
linetype                     : "Rodzaj linii"
bezier                       : "Bezier"
cornered                     : "Cornered"
options                      : "Opcje ..."
export                       : "Exportuj"
sql                          : "Sql ..."
image                        : "Obraz ..."
help                         : "Pomoc"
index                        : "Index"
changes                      : "Zmiany"
shortcuts                    : "Skróty klawiszowe"
feedback                     : "Zgłoś błąd"
about                        : "O nas"
guest                        : "Gość"
login                        : "Login"
logout                       : "Wyloguj"
settings                     : "Ustawienia"
panel                        :
history                      : "Historia"
last_versions_label          : "Ostatnie 10 wersji schematu:"
properties                   : "Właściwości"
properties_schema_name       : "Nazwa Schematu:"
properties_database          : "Baza danych:"
comments                     : "Komentarze"
comment_placeholder          : "Wpisz swój komentarz tutaj"
send                         : "Wyślij"
dialog                       :
new_schema                   : "Nowy schemat"
new_schema_title             : "Tytuł"
new_schema_database          : "Baza danych"
new_schema_type_info         : """Wybór "ogólny" typu bazy danychpozwala na generowanie SQL dla wszystkich baz danych; Ale będziesz miał dostęp do tylko podstawowych typów danych."""
new_schema_create_new        : "Stwórz nowy schemat"
load_schema                  : "Wczytaj Schemat"
load_schema_your_schemas     : "Twoje Schematy:"
load_schema_schema_name      : "Nazwy Schematów"
load_schema_database         : "Baza Danych"
load_schema_last_save        : "Ostatni zapis"
load_schema_shared_with_you  : "Schematy udostępnione przez Ciebie:"
load_schema_owner            : "Właściciel"
load_schema_no_schemas       : "Nie zapisałś żadnych schematów"
load_schema_no_shared_schemas: "Nie ma żadnych schematów udostępnionych przez Ciebie"
saveas                       : "Zapisz jako"
saveas_title                 : "Tytuł"
saveas_button                : "Zapisz jako"
templates                    : "Szablony"
templates_schema_name        : "Nazwa Schematu"
templates_database           : "Baza Danych"
templates_description        : "opis"
properties                   : "Właściwości schematu"
properties_title             : "Tytuł"
properties_publish           : "Opublikuj jako szablon"
properties_template_info     : "(Szblon jest widoczny dla każdego użytkownika)"
properties_delete_schema     : "Usuń schemat"
properties_delete_alert      : "(Usuniesz ten schemat na zawsze oraz powiązane z nim komentarze)"
properties_save              : "Zapisz zmiany"
share                        : "Udostpnij"
share_info                   : "Możesz udostpnić ten program maksymalnie 5 użytkownikomu"
share_email                  : "E-mail"
share_access                 : "Dostęp"
share_read_only              : "Tylko do odczytu"
share_read_write             : "Odczyt i zapis"
share_send_email             : "Wylij maila z zaproszeniem"
share_invite_button          : "Zapro"
share_collaborators          : "Udostępnionym:"
import                       : "Importuj  Sql"
login_email                  : "E-mail"
login_password               : "Hasło"
login_button                 : "Login"
login_forgot_password        : "Zapomniałem hasło"
options                      : "Opcje"
options_line_colors          : "Kolor linii"
options_invert_line_direction: "Zmień kierunek linii"
options_show_fk_icon         : "Pokaż ikone klucza obcego"
options_show_not_null_icon   : "Pokaż icone wartości NULL"
options_show_default_values  : "Pokaż wartści domyślne"
options_language             : "Język"
options_save_changes         : "Zapisz zmiany"
export_sql                   : "Wyeksportuj jako SQL"
export_sql_generate          : "Generuj SQL"
export_sql_download          : "Ściągnij plik SQL"
export_image                 : "Wyeksportuj jako obraz"
export_image_zoomin          : "Przybliż"
export_image_zoomout         : "Oddal"
export_image_reset           : "Reset"
export_image_open_in_new_tab : "Otwórz obraz w nowym oknie"
help                         : "Pomoc"
shortcuts                    : "Skróty Klawiszowe"
help_changelog               : "Zmiany"
feedback                     : "Powiadomienie"
feedback_type                : "Typ Powiadomienia"
feedback_bug                 : "Report Bugów"
feedback_feature             : "Zgłoszanie Pomysłów"
feedback_help                : "Pomoc"
feedback_other               : "Inne"
feedback_message             : "Wiadomość"
feedback_button              : "Wyślij powiadomienie"
about                        : "O dbdesigner.net"
user_settings                : "Ustawienia Użytkownika"
user_settings_username       : "Nazwa Użytkownika"
user_settings_email          : "E-mail"
user_settings_save           : "Zapisz Zmiany"
login                        : "Login"
close                        : "Zamknij"
back                         : "Cofnij"
designer                     :
save_note_edit               : "Zapisz"
cancel_note_edit             : "Anuluj"
delete_note                  : "Usuń"
table_name                   : "Nazwa Tabeli"
table_comment                : "Komentarz Tabeli"
table_save                   : "Zapisz"
table_cancel                 : "Anuluj"
table_delete                 : "Usuń Tabele"
table_clone                  : "Zklonuj Tabele"
table_add_field              : "Dodaj Pole"
field_name                   : "Nazwa"
field_type                   : "Typ"
field_size                   : "Rozmiar"
field_default                : "Domyślna"
field_allow_nulls            : "Zezwalaj na wartości null"
field_primary_key            : "Primary Key"
field_foreign_key            : "Foreign Key"
field_save                   : "Zapisz"
field_update                 : "Update"
field_cancel                 : "Anuluj"
field_delete                 : "Usuń Pole"
field_delete_alert           : "Jesteś pewien, że chcesz usunąć to pole?\n(przytrzymaj shift, aby usuwać bez powiadomienia)"
field_ref_table              : "Odśwież Tabele"
field_ref_field              : "Odśwież Pole"
alerts                       :
delete_schema                : "Jesteś pewien, że chcesz usunąć ten schemat?"
server_error                 : "Wystąpił błąd serwera"
schema_owner_error           : "Tylko właściciel może zmienić ustawienia schematu"
login_to_use_this_function   : "Zaloguj się, aby skorzystać z tej funkcji"

